backend:
  name: github
  repo: VercaNiCa/VercaNiCa.github.io  # <- Twoje repo
  branch: main  # <- branch, na którym chcesz zapisywać wpisy

media_folder: "images/uploads"  # folder, gdzie będą wrzucane zdjęcia
public_folder: "/images/uploads"

collections:
  - name: "posts"
    label: "Posty"
    folder: "_posts"  # folder, w którym będą przechowywane wpisy (możesz sam ustalić)
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Tytuł", name: "title", widget: "string" }
      - { label: "Data", name: "date", widget: "datetime" }
      - { label: "Treść", name: "body", widget: "markdown" }
